#include "openzen.h"
#include "generated_names.h"  // OZ_BRIDGE_FQCN — generated by build.gradle ext.obfuscateJar

#include <cstring>

namespace openzen::classes {

namespace {
    bool check_and_clear(JNIEnv* env, const char* where) {
        if (env->ExceptionCheck()) {
            log::error("JNI exception at %s", where);
            env->ExceptionDescribe();
            env->ExceptionClear();
            return true;
        }
        return false;
    }

    jvmtiEnv* get_jvmti(JavaVM* vm) {
        jvmtiEnv* jvmti = nullptr;
        if (vm->GetEnv((void**)&jvmti, JVMTI_VERSION_1_2) != JNI_OK || !jvmti) {
            log::error("GetEnv(JVMTI_VERSION_1_2) failed");
            return nullptr;
        }
        return jvmti;
    }

    jobject class_loader_of(JNIEnv* env, jclass cls) {
        jclass classCls = env->FindClass("java/lang/Class");
        if (!classCls) return nullptr;
        jmethodID mid = env->GetMethodID(classCls, "getClassLoader",
                                          "()Ljava/lang/ClassLoader;");
        if (!mid) return nullptr;
        jobject loader = env->CallObjectMethod(cls, mid);
        env->DeleteLocalRef(classCls);
        if (env->ExceptionCheck()) {
            env->ExceptionClear();
            return nullptr;
        }
        return loader;
    }
}

jobject find_game_class_loader(JavaVM* vm, JNIEnv* env) {
    jvmtiEnv* jvmti = get_jvmti(vm);
    if (!jvmti) return nullptr;

    jint count = 0;
    jclass* classes = nullptr;
    jvmtiError rc = jvmti->GetLoadedClasses(&count, &classes);
    if (rc != JVMTI_ERROR_NONE || !classes) {
        log::error("GetLoadedClasses failed: %d", (int)rc);
        return nullptr;
    }
    log::info("GetLoadedClasses returned %d classes", (int)count);

    jobject game_loader = nullptr;
    const char* needle = "Lnet/minecraft/client/Minecraft;";

    for (jint i = 0; i < count && !game_loader; ++i) {
        char* sig = nullptr;
        if (jvmti->GetClassSignature(classes[i], &sig, nullptr) != JVMTI_ERROR_NONE) continue;
        if (sig && std::strcmp(sig, needle) == 0) {
            log::info("Matched class signature %s", sig);
            game_loader = class_loader_of(env, classes[i]);
        }
        if (sig) jvmti->Deallocate((unsigned char*)sig);
    }

    jvmti->Deallocate((unsigned char*)classes);

    if (!game_loader) {
        log::error("Minecraft class not found among loaded classes");
        return nullptr;
    }
    return game_loader;
}

jclass load_dll_bootstrap(JNIEnv* env, jobject game_loader,
                          const std::wstring& jar_path) {
    // Build java.io.File(jar_path)
    jclass fileCls = env->FindClass("java/io/File");
    if (!fileCls) { check_and_clear(env, "FindClass File"); return nullptr; }
    jmethodID fileCtor = env->GetMethodID(fileCls, "<init>", "(Ljava/lang/String;)V");
    if (!fileCtor) { check_and_clear(env, "GetMethodID File.<init>"); return nullptr; }
    jstring jarStr = env->NewString(
        reinterpret_cast<const jchar*>(jar_path.c_str()),
        static_cast<jsize>(jar_path.size()));
    jobject file = env->NewObject(fileCls, fileCtor, jarStr);
    if (check_and_clear(env, "new File")) return nullptr;

    // file.toURI()
    jmethodID toURI = env->GetMethodID(fileCls, "toURI", "()Ljava/net/URI;");
    jobject uri = env->CallObjectMethod(file, toURI);
    if (check_and_clear(env, "File.toURI")) return nullptr;

    // uri.toURL()
    jclass uriCls = env->FindClass("java/net/URI");
    jmethodID toURL = env->GetMethodID(uriCls, "toURL", "()Ljava/net/URL;");
    jobject url = env->CallObjectMethod(uri, toURL);
    if (check_and_clear(env, "URI.toURL")) return nullptr;

    // URL[] urls = { url };
    jclass urlCls = env->FindClass("java/net/URL");
    jobjectArray urls = env->NewObjectArray(1, urlCls, url);
    if (check_and_clear(env, "NewObjectArray URL[]")) return nullptr;

    // new URLClassLoader(urls, gameLoader)
    jclass urlclCls = env->FindClass("java/net/URLClassLoader");
    if (!urlclCls) { check_and_clear(env, "FindClass URLClassLoader"); return nullptr; }
    jmethodID urlclCtor = env->GetMethodID(urlclCls, "<init>",
        "([Ljava/net/URL;Ljava/lang/ClassLoader;)V");
    if (!urlclCtor) { check_and_clear(env, "GetMethodID URLClassLoader.<init>"); return nullptr; }
    jobject urlcl = env->NewObject(urlclCls, urlclCtor, urls, game_loader);
    if (check_and_clear(env, "new URLClassLoader")) return nullptr;
    log::info("URLClassLoader constructed with parent=gameLoader");

    // urlcl.loadClass(OZ_BRIDGE_FQCN)  (the build-time-obfuscated GameLoaderBridge)
    //
    // We deliberately load GameLoaderBridge - not DllBootstrap - because the
    // bridge's job is to re-define every class in zen.jar onto the game
    // class loader so retransformed Minecraft classes can resolve our patch
    // handlers (defining-loader equality). DllBootstrap is then loaded by
    // the game loader from the bridge.
    //
    // The build renames every OpenZen class to an opaque generated name (see
    // build.gradle ext.obfuscateJar). It also emits generated_names.h with the
    // bridge's new FQCN as OZ_BRIDGE_FQCN, so this stays in lockstep with the
    // embedded jar without any hard-coded class name. The bridge's
    // load(String, ClassLoader) method name is preserved by the rename, so the
    // GetStaticMethodID(bridge_cls, "load", ...) lookup in main.cpp still works.
    jclass classLoaderCls = env->FindClass("java/lang/ClassLoader");
    jmethodID loadClass = env->GetMethodID(classLoaderCls, "loadClass",
        "(Ljava/lang/String;)Ljava/lang/Class;");
    jstring name = env->NewStringUTF(OZ_BRIDGE_FQCN);
    jobject loaded = env->CallObjectMethod(urlcl, loadClass, name);
    if (check_and_clear(env, "URLClassLoader.loadClass GameLoaderBridge")) return nullptr;
    if (!loaded) {
        log::error("loadClass returned null for GameLoaderBridge");
        return nullptr;
    }
    log::info("GameLoaderBridge class loaded via URLClassLoader");
    return static_cast<jclass>(loaded);
}

} // namespace openzen::classes
